### ISSUE TITLE
Things to investigate

### ISSUE THREAD

**Issue by JamesSmith1202** [mkorsun/softdev2_FinalProject#1]
1. Syncing Issue:
- Investigate how to actually stream from websites to the server
- How to stream that music to many users(HTTP Streaming?)

2. Internet Speed for streaming 
- Speed of droplet
- Can we downgrade sound quality
3. Connecting many people at once
4. Queuing songs from many websites
5. Checking the number of people currently in a room to shut off the streaming for those rooms

TBC...

**Comment by mkorsun** [comment]
changed plan
